# This is a basic workflow to help you get started with Actions

name: basic-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          persist-credentials: true  # Needed to push back

      - name: Run PowerShell script # a github actions scripting action
        shell: pwsh
        run: |
          Write-Host "Running script.ps1..."
          .\script.ps1
          
      - name: Commit and push changes
        shell: pwsh
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *
          if (git diff --cached --quiet) {
              Write-Host "No changes to commit."
          } else {
              git commit -m "Replace #DEBUG comments"
              git push
          }
